Translate this [image](https://upload.wikimedia.org/wikipedia/commons/9/95/Finance_Markov_chain_example_state_space.svg) of a Markov process into a transition matrix.  If the initial state of the system (time=0) is "bear," what will be the probability distribution at time=3?  What about time=infinity (the steady state probability distribution).

In [47]:
import numpy as np
import pandas as pd

In [14]:
market = [[.9,.075,.025],
[.15,.8,.05],
[.25,.25,.5]]

In [15]:
def bull(probability):
    if probability < .025:
        return (3,"stagnant")
    elif probability < .01:
        return (2,"bear")
    elif probability < 1:
        return (1,"bull")

In [16]:
def bear(probability):
    if probability < .15:
        return (1,"bull")
    elif probability < .2:
        return (3,"stagnant")
    elif probability < 1:
        return (2,"bear")

In [17]:
def stagnant(probability):
    if probability < .25:
        return (1,"bull")
    elif probability < .5:
        return (3,"bear")
    elif probability < 1:
        return (2,"stagnant")

In [53]:
runs = []
for x in range(0,100):
    state = 1
    run = [1]
    for i in range(0,3):
        probability = np.random.random(1)
        if(state == 1):
            state, stateName = bull(probability)
        elif(state == 2):
            state, stateName = bear(probability)
        elif(state == 3):
            state, stateName = stagnant(probability)
        run.append(state)
    runs.append(run)

In [54]:
pd.DataFrame(runs, columns=[0,1,2,3])

    0  1  2  3
0   1  1  1  1
1   1  1  1  1
2   1  1  1  1
3   1  1  1  1
4   1  1  1  1
5   1  1  1  1
6   1  1  1  1
7   1  1  1  1
8   1  1  1  1
9   1  1  1  1
10  1  1  1  1
11  1  1  1  1
12  1  1  1  1
13  1  1  1  1
14  1  1  1  1
15  1  1  1  1
16  1  1  1  1
17  1  1  1  1
18  1  1  1  3
19  1  1  1  1
20  1  1  1  1
21  1  1  1  3
22  1  1  3  2
23  1  1  1  1
24  1  1  1  1
25  1  3  2  1
26  1  1  1  1
27  1  1  1  1
28  1  1  1  1
29  1  1  1  1
.. .. .. .. ..
70  1  1  3  2
71  1  1  1  1
72  1  1  1  1
73  1  1  1  1
74  1  1  1  1
75  1  1  1  1
76  1  1  1  1
77  1  1  1  1
78  1  1  1  1
79  1  1  1  1
80  1  1  1  1
81  1  1  1  1
82  1  1  1  1
83  1  1  1  1
84  1  1  1  1
85  1  1  1  1
86  1  1  1  1
87  1  1  1  1
88  1  1  1  1
89  1  1  1  1
90  1  1  1  1
91  1  1  1  1
92  1  1  1  1
93  1  1  1  1
94  1  1  1  1
95  1  1  1  1
96  1  1  1  1
97  1  1  1  1
98  1  1  1  1
99  1  1  1  1

[100 rows x 4 columns]