# Getting started

Once you've chosen your scenario, download the data from [the Iowa website](https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy) in csv format. Start by loading the data with pandas. You may need to parse the date columns appropriately.

In [1]:
#%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
## Load the data into a DataFrame
df = pd.read_csv('../assets/Iowa_Liquor_sales_sample_10pct.csv')
df = df.dropna()
#df = df[df["Zip Code"] != 56201]


## Transform the dates if needed, e.g.
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")

def stripDollarSign(string):
    return float(string.strip("$"))

df["State Bottle Cost"] = df["State Bottle Cost"].apply(stripDollarSign)
df["State Bottle Retail"] = df["State Bottle Retail"].apply(stripDollarSign)
df["Sale (Dollars)"] = df["Sale (Dollars)"].apply(stripDollarSign)

df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 269258 entries, 0 to 270954
Data columns (total 18 columns):
Date                     269258 non-null datetime64[ns]
Store Number             269258 non-null int64
City                     269258 non-null object
Zip Code                 269258 non-null object
County Number            269258 non-null float64
County                   269258 non-null object
Category                 269258 non-null float64
Category Name            269258 non-null object
Vendor Number            269258 non-null int64
Item Number              269258 non-null int64
Item Description         269258 non-null object
Bottle Volume (ml)       269258 non-null int64
State Bottle Cost        269258 non-null float64
State Bottle Retail      269258 non-null float64
Bottles Sold             269258 non-null int64
Sale (Dollars)           269258 non-null float64
Volume Sold (Liters)     269258 non-null float64
Volume Sold (Gallons)    269258 non-null float64
dtypes: datetime64[ns](1), float64(7), int64(5), object(5)
memory usage: 39.0+ MB

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.00,2.38
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.50,0.40
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,12.59,18.89,24,453.36,24.00,6.34
3,2016-02-03,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,9.50,14.25,6,85.50,10.50,2.77
4,2015-08-18,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,7.20,10.80,12,129.60,21.00,5.55
5,2015-04-20,2569,CEDAR RAPIDS,52402,57.0,Linn,1041100.0,AMERICAN DRY GINS,205,31473,New Amsterdam Gin,1750,13.32,19.98,6,119.88,10.50,2.77
6,2015-08-05,2596,OTTUMWA,52501,90.0,Wapello,1051010.0,AMERICAN GRAPE BRANDIES,85,52806,Korbel Brandy,750,6.66,9.99,3,29.97,2.25,0.59
7,2015-06-25,3456,CLEAR LAKE,50428,17.0,Cerro Gordo,1012100.0,CANADIAN WHISKIES,65,10628,Canadian Club Whisky,1750,15.75,23.63,2,47.26,3.50,0.92
8,2016-01-04,4757,BONDURANT,50035,77.0,Polk,1032080.0,IMPORTED VODKA,370,34006,Absolut Swedish Vodka 80 Prf,750,11.49,17.24,4,68.96,3.00,0.79
9,2015-11-10,4346,SHELLSBURG,52332,6.0,Benton,1081315.0,CINNAMON SCHNAPPS,65,82610,Dekuyper Hot Damn!,1000,7.62,11.43,2,22.86,2.00,0.53

# Explore the data

Perform some exploratory statistical analysis and make some plots, such as histograms of transaction totals, bottles sold, etc.

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
sns.heatmap(df.corr())

## Record your findings

Be sure to write out anything observations from your exploratory analysis.

# Mine the data
Now you are ready to compute the variables you will use for your regression from the data. For example, you may want to
compute total sales per store from Jan to March of 2015, mean price per bottle, etc. Refer to the readme for more ideas appropriate to your scenario.

Pandas is your friend for this task. Take a look at the operations [here](http://pandas.pydata.org/pandas-docs/stable/groupby.html) for ideas on how to make the best use of pandas and feel free to search for blog and Stack Overflow posts to help you group data by certain variables and compute sums, means, etc. You may find it useful to create a new data frame to house this summary data.

# Refine the data
Look for any statistical relationships, correlations, or other relevant properties of the dataset.

In [5]:
categories = ["County"]
for category in categories:
    series = df[category]
    dummies = pd.get_dummies(series, prefix=category)
    df = pd.concat([df, dummies], axis=1)
df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,County_Wapello,County_Warren,County_Washington,County_Wayne,County_Webster,County_Winnebago,County_Winneshiek,County_Woodbury,County_Worth,County_Wright
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2016-02-11,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2016-02-03,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-08-18,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

# Build your models

Using scikit-learn or statsmodels, build the necessary models for your scenario. Evaluate model fit.

In [6]:
#import statsmodels.formula.api as smf

#statsModelLM = smf.ols(formula='Sale ~ Volume', data=df).fit()
#print statsModelLM.summary()

from sklearn import linear_model

baselist = ["Volume Sold (Liters)"]
X = df[baselist]
y = df["Sale (Dollars)"]
lm = linear_model.LinearRegression()
model = lm.fit(X,y)
predictions = model.predict(X)

print lm.score(X,y)

0.716347791216

In [7]:
#print df.columns.values[18:].tolist()

X = df[baselist + df.columns.values[18:].tolist()]
y = df["Sale (Dollars)"]
lm = linear_model.LinearRegression()
model = lm.fit(X,y)
predictions = model.predict(X)

print lm.score(X,y)

0.717623975898

In [8]:
geographyTypes = ["County","City","Zip Code"]
dataframes = []

for geoType in geographyTypes:

    itemList = []
    scoreList = []
    totalSales = []
    totalBottlesSold = []
    pricePerBottle = []
    margin = []
    pricePerLiter = []
    
    
    geographic = sorted(set(df[geoType]))

    for g in geographic:
        mask = df[geoType] == g
        itemList.append(g)
        
        tempdf = df[mask]
        
        totalSales.append(sum(tempdf["Sale (Dollars)"]))
        totalBottlesSold.append(tempdf["Bottles Sold"].sum())
        pricePerBottle.append(np.mean(tempdf["State Bottle Retail"]))
        margin.append(np.mean(tempdf["State Bottle Retail"] - tempdf["State Bottle Cost"]))
        pricePerLiter.append(sum(tempdf["Sale (Dollars)"]) / sum(tempdf["Volume Sold (Liters)"]))
        
        if(geoType == "County"):
            X = df[mask][["Bottles Sold","State Bottle Retail", geoType + "_" + g]]
        else:
            X = df[mask][["Bottles Sold","State Bottle Retail"]] 

        y = df[mask]["Sale (Dollars)"]

        lm = linear_model.LinearRegression()

        model = lm.fit(X,y)
        predictions = model.predict(X)
        
        scoreList.append(lm.score(X,y))


    output = pd.DataFrame(
        {geoType:itemList,"R^2Score": scoreList,
            "TotalSales": totalSales,
            "TotalBottlesSold": totalBottlesSold,
            "AvgPriceperBottle": pricePerBottle,
            "MarginPerBottle": margin,
            "PricePerLiter": pricePerLiter
        })

    output.to_csv('../assets/formattedIowaAlcoholSalesBy'+ geoType + '.csv')
    
    dataframes.append(output)

In [9]:
countyDataFrame = dataframes[0]
cityDataFrame = dataframes[1]
zipcodeDataFrame = dataframes[2]

In [10]:
countyDataFrame.sort_values("TotalSales",ascending=False,inplace=True)
countyDataFrame.head(5)

,AvgPriceperBottle,County,MarginPerBottle,PricePerLiter,R^2Score,TotalBottlesSold,TotalSales
76,15.202882,Polk,5.077717,15.419951,0.745034,579677,7.747219e+06
56,14.233033,Linn,4.754082,14.326814,0.695870,245771,3.139999e+06
81,14.437241,Scott,4.821982,15.139441,0.686150,204915,2.457277e+06
51,15.377705,Johnson,5.136183,16.029407,0.598849,147638,2.077858e+06
6,14.038912,Black Hawk,4.689621,14.611529,0.541959,172713,1.928017e+06

In [11]:
cityDataFrame.sort_values("TotalSales",ascending=False,inplace=True)
cityDataFrame.head(5)

,AvgPriceperBottle,City,MarginPerBottle,PricePerLiter,R^2Score,TotalBottlesSold,TotalSales
90,14.981637,DES MOINES,5.002371,15.865613,0.736643,344151,4380886.26
51,14.202422,CEDAR RAPIDS,4.743563,14.531323,0.694650,194525,2486949.08
81,13.706269,DAVENPORT,4.578247,14.642437,0.685822,153200,1697702.84
175,15.024816,IOWA CITY,5.018575,15.502986,0.644152,93923,1250666.19
358,13.462237,WATERLOO,4.495614,14.927784,0.531354,117206,1211603.55

In [12]:
zipcodeDataFrame.sort_values("TotalSales",ascending=False,inplace=True)
zipcodeDataFrame.head(5)

,AvgPriceperBottle,MarginPerBottle,PricePerLiter,R^2Score,TotalBottlesSold,TotalSales,Zip Code
90,17.650358,5.891215,17.621886,0.686394,89891,1325170.74,50314
94,17.226750,5.749438,15.997775,0.770759,84708,1300498.14,50320
358,14.187930,4.739043,14.082607,0.699809,89329,1154143.14,52402
323,15.106018,5.045029,15.665350,0.639417,81693,1080449.51,52240
4,15.724516,5.252892,14.706226,0.854616,64738,931101.58,50010

In [13]:
print "Average of County R^2 Scores: ", np.mean(dataframes[0]["R^2Score"])
print "Average of City R^2 Scores: ", np.mean(dataframes[1]["R^2Score"])
print "Average of Zipcode R^2 Scores: ", np.mean(dataframes[2]["R^2Score"])

Average of County R^2 Scores:  0.791390541369
Average of City R^2 Scores:  0.781958153293
Average of Zipcode R^2 Scores:  0.7725564866

## Plot your results

Again make sure that you record any valuable information. For example, in the tax scenario, did you find the sales from the first three months of the year to be a good predictor of the total sales for the year? Plot the predictions versus the true values and discuss the successes and limitations of your models

In [14]:
sns.heatmap(dataframes[0].corr())

In [15]:
fig, axs = plt.subplots(2,2)
dataframes[0].plot(kind="scatter", y="TotalSales", x="TotalBottlesSold", ax=axs[0,0], figsize=(16,8))
dataframes[0].plot(kind="scatter", y="TotalSales", x="AvgPriceperBottle", ax=axs[0,1], figsize=(16,8))
dataframes[0].plot(kind="scatter", y="TotalSales", x="MarginPerBottle", ax=axs[1,0], figsize=(16,8))
dataframes[0].plot(kind="scatter", y="TotalSales", x="PricePerLiter", ax=axs[1,1], figsize=(16,8))

In [16]:
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics

#dataframes[0] is county
X = dataframes[0][["TotalBottlesSold","AvgPriceperBottle","MarginPerBottle","PricePerLiter"]]
y = dataframes[0]["TotalSales"]

model = lm.fit(X,y)

# Perform 6-fold cross validation
scores = cross_val_score(model, X, y, cv=6)
print "Cross-validated Scores:", scores
# Make cross validated predictions
predictions = cross_val_predict(model, X, y, cv=6)
plt.scatter(y, predictions)
accuracy = metrics.r2_score(y, predictions)
print "Cross-Predicted Accuracy:", accuracy

Cross-validated Scores: [ 0.99513305  0.95971779  0.63701959 -0.28890424  0.15892351 -6.34191698]
Cross-Predicted Accuracy: 0.996633093263

In [17]:
#dataframes[1] is City
X = dataframes[1][["TotalBottlesSold","AvgPriceperBottle","MarginPerBottle","PricePerLiter"]]
y = dataframes[1]["TotalSales"]

model = lm.fit(X,y)

# Perform 6-fold cross validation
scores = cross_val_score(model, X, y, cv=6)
print "Cross-validated Scores:", scores
# Make cross validated predictions
predictions = cross_val_predict(model, X, y, cv=6)
plt.scatter(y, predictions)
accuracy = metrics.r2_score(y, predictions)
print "Cross-Predicted Accuracy:", accuracy

Cross-validated Scores: [   0.98976608    0.92175691   -1.23911295  -13.88832383  -27.64864644
 -233.68104566]
Cross-Predicted Accuracy: 0.991989055951

In [18]:
#dataframes[2] is Zip code
X = dataframes[2][["TotalBottlesSold","AvgPriceperBottle","MarginPerBottle","PricePerLiter"]]
y = dataframes[2]["TotalSales"]

model = lm.fit(X,y)

# Perform 6-fold cross validation
scores = cross_val_score(model, X, y, cv=6)
print "Cross-validated Scores:", scores
# Make cross validated predictions
predictions = cross_val_predict(model, X, y, cv=6)
plt.scatter(y, predictions)
accuracy = metrics.r2_score(y, predictions)
print "Cross-Predicted Accuracy:", accuracy

Cross-validated Scores: [  8.70608261e-01   3.97557879e-01   5.50724434e-01  -1.71793048e+01
  -5.03835384e+01  -5.31428933e+02]
Cross-Predicted Accuracy: 0.94147951884

# Present the Results

Present your conclusions and results. If you have more than one interesting model feel free to include more than one along with a discussion. Use your work in this notebook to prepare your write-up.

[Alex's Project 3 Blog Post](https://tamisalex.wordpress.com/)